apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "k8s.armillary.io/v1alpha1",
          "kind": "NodeImagePool",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "k8s-node-image-pool-operator"
            },
            "name": "nodeimagepool-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-02-04T19:04:39Z"
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: k8s-node-image-pool-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeImagePool is the Schema for the nodeimagepools API.
      displayName: Node Image Pool
      kind: NodeImagePool
      name: nodeimagepools.k8s.armillary.io
      version: v1alpha1
  description: Allows for nodes to serve images they have locally cached for other
    nodes in the cluster to efficiently pull from
  displayName: Kubernetes Node Image Pool Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - k8s.armillary.io
          resources:
          - nodeimagepools
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - k8s.armillary.io
          resources:
          - nodeimagepools/finalizers
          verbs:
          - update
        - apiGroups:
          - k8s.armillary.io
          resources:
          - nodeimagepools/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: k8s-node-image-pool-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: k8s-node-image-pool-operator
          control-plane: controller-manager
        name: k8s-node-image-pool-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: k8s-node-image-pool-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: k8s-node-image-pool-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: k8s-node-image-pool-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: k8s-node-image-pool-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - image
  - cache
  - mirror
  - proxy
  - kubernetes
  - openshift
  links:
  - name: K8s Node Image Pool Operator
    url: https://k8s-node-image-pool-operator.domain
  maintainers:
  - email: ken@kenmoini.com
    name: Ken Moini
  maturity: alpha
  provider:
    name: Armillary
    url: https://armillary.io
  version: 0.0.1
