---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s.armillary.io
  resources:
  - nodeimagepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.armillary.io
  resources:
  - nodeimagepools/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.armillary.io
  resources:
  - nodeimagepools/status
  verbs:
  - get
  - patch
  - update
