apiVersion: k8s.armillary.io/v1alpha1
kind: NodeImagePool
metadata:
  name: nodeimagepool-sample
spec:
  mirrorFiltering:
    - quay.io/kenmoini
  cachePools:
    - name: control-plane-pool
      matchLabels:
        node-role.kubernetes.io/master: ''
  cacheConsumers:
    - name: worker-pool
      matchLabels:
        node-role.kubernetes.io/worker: ''