apiVersion: k8s.armillary.io/v1alpha1
kind: NodeImagePool
metadata:
  labels:
    app.kubernetes.io/name: k8s-node-image-pool-operator
    app.kubernetes.io/managed-by: kustomize
  name: nodeimagepool-sample
spec:
  # TODO(user): Add fields here
